config/routes.rb
DevBootFace::Application.routes.draw do
  root 'home#index'
  devise_for :users

  resources :users do
  	resources :posts
  end

  resources :posts do
  	resources :comments
  end

  resources :comments do
  	resources :commments
  end
  # get '/posts', to: 'posts#show'

  resources :groups do
    resources :users
  end
  # You can have the root of your site routed with "root"

  end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  belongs_to :user
end

app/models/group.rb
class Group < ActiveRecord::Base

  has_and_belongs_to_many :users
  has_many :posts

end

app/models/post.rb
class Post < ActiveRecord::Base

  has_many :comments, as: :commentable
  belongs_to :user
  belongs_to :group

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :comments
  has_many :posts
  has_and_belongs_to_many :groups

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name
    devise_parameter_sanitizer.for(:sign_up) << :last_name
    devise_parameter_sanitizer.for(:account_update) << :first_name
    devise_parameter_sanitizer.for(:account_update) << :last_name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post_id = params[:post_id]
    @user_id = current_user.id
    @comment = Comment.new()
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to "/posts/#{params[:commentable_id]}"
    else
      render 'new'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content,:user_id,:commentable_id, :commentable_type)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

	def index
		@groups = Group.all
	end

	def new
		@group = Group.new
	end

	def create
		@group = Group.new(group_params)
		if @group.save
			redirect_to groups_path
		else
			render 'new'
		end
	end

	def show
		@group = Group.where(id: params[:id]).first
	end

	def edit
		@group = Group.where(id: params[:id]).first
	end

	def update
		@group = Group.where(id: params[:id]).first
		if @group.update(params[:group].permit(:name, :description))
			redirect_to group_path
		else
			render 'edit'
		end		
	end

private

	def group_params
		params.require(:group).permit(:name, :description)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

end

app/controllers/posts_controller.rb
require 'rinku'

class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
  	@post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
    	current_user.posts << @post
			redirect_to posts_path
		else
			render 'new'
		end		
  end

  def show
		@post = Post.where(id: params[:id]).first
	end

	def edit
		@post = Post.where(id: params[:id]).first
	end

	def update
		@post = Post.where(id: params[:id]).first
		if @post.update(params[:post].permit(:title, :content))
			redirect_to post_path
		else
			render 'edit'
		end		
	end

	def destroy
		Post.delete(params[:id])
		redirect_to posts_path
	end

private
	
	def post_params
		params.require(:post).permit(:content, :user)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<h1> Create Comment </h1>

<%= form_for @comment do |f| %>
<p>
  <%= f.label :content %>
  <%= f.text_area :content %>
</p>
<%= f.hidden_field :commentable_type, value: Post %>
<%= f.hidden_field :commentable_id, value: @post_id%>
<%= f.hidden_field :user_id, value: @user_id%>
<%= f.submit %>
<% end %>
<br>


<%= link_to 'Back', posts_path %>

app/views/groups/edit.html.erb
<h1> Edit Group </h1>

<p> Hi there</p>
<p>Edit your group, filthy animal</p>

<%= form_for @group do |f| %>
<p>
	<%= f.label :name %>
	<%= f.text_area :name %> 
</p>
<p>
	<%= f.label :description %>
	<%= f.text_area :description %> 
</p>
<%= f.submit %>
<% end %>


<br>


<%= link_to 'Back', groups_path %>
<%= link_to 'Home', posts_path %>

app/views/groups/index.html.erb
<h1>Groups Home</h1>
<%= link_to 'Home', posts_path %>

<%= link_to 'New Group', new_group_path %>
	<% if @groups.any? %>
  <% @groups.each do |group| %>
    <h4><%= link_to group.name, group_path(group) %></h4>
    <%= group.description %>
    <hr>
  <% end %>
<% end %>

app/views/groups/new.html.erb
<%= form_for @group do |f| %>
	<p>
		<%= f.label :name %><br>
		<%= f.text_area :name %>
	</p>
		<%= f.label :description %><br>
		<%= f.text_area :description %>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/groups/show.html.erb
<p><strong>Group Name: </strong>
	<%= @group.name %></p>
<p><strong>Description: </strong>
	<%= @group.description %></p>
<p><strong>Members: </strong></p>
	<% @group.users.each do |user| %>
		<p><%= user.id %></p>
	<% end %>

<p><%= link_to 'New Group Post', new_group_path(@group.id) %></p>
<%= link_to 'Back', groups_path %>
<%= link_to 'Edit', edit_group_path(@group) %>

app/views/home/index.html.erb
<h1> Welcome to DevBootFace </h1>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<% if current_user %>
<%= link_to 'Home', posts_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DevBootFace</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
  <p class="alert alert-notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-error"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1> Edit Post </h1>

<p> Hi there</p>
<p>Edit your post, filthy animal</p>

<%= form_for @post do |f| %>
<p>
	<%= f.label :content %>
	<%= f.text_area :content %> 
</p>
<%= f.submit %>
<% end %>
<br>


<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Posts Home</h1>
<%= link_to 'Groups', groups_path %>

<%= link_to 'New Post', new_post_path %>
	<% if @posts.any? %>
  <% @posts.each do |post| %>
    <h4><%= link_to post.user.first_name, post_path(post) %></h4>
    <%= raw Rinku.auto_link(post.content) %>
    <hr>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
	
		<%= f.label :content %><br>
		<%= f.text_area :content %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>
	

app/views/posts/post_new.html.erb
<%= form_for @post do |f| %>
	<p>
		<%= f.label :author %><br>
		<%= f.text_field :author %>
	</P>

	<p>
		<%= f.label :content %><br>
		<%= f.text_area :content %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>
	

app/views/posts/show.html.erb
<p><strong>User: </strong>
	<%= @post.user_id %></p>
<p><strong>Post: </strong>
	<%= @post.content %></p>
<p><strong>Comments:</strong> </p>
<% @post.comments.each do |comment| %>
  <p> <%= comment.content %> </p>
<% end %>

<p><%= link_to 'Add Comment', new_post_comment_path(@post.id) %></p>
<%= link_to 'Back', posts_path %>
<%= link_to 'Edit', edit_post_path(@post) %>
<%= link_to 'Destroy', @post, :method => :delete, :confirm => "Are you sure?" %>